### ISSUE TITLE
Theme CSS Messes with Table Border/ A links in Certain Themes

### ISSUE THREAD

**Issue by tcbutler320** [tcbutler320/jek#23]
The default css for tables (black borders) or a links, does not work for all themes. If each theme requires a table css style, it would look something like the following

```css
.dark {
    color: white;
    background-color: black;
}

/* this must be done for certain themes to see table lines */
.dark th, td {
    border:1px solid white;
}

.dark a {
    color: white;
}

```
